USE Keeley

create table DBO.AdministratorPortfolio_hst(
	AdministratorPortfolioID int not null,
	FundId int not null,
	ReferenceDate datetime not null,
	InstrumentMarketId int,
	InstrumentName varchar(100),
	IsAccrual bit not null,
	NetPosition numeric(27,8) not null,
	MarketValue numeric(27,8) not null,
	Price numeric(27,8) not null,
	FXRate numeric(27,8) not null,
	RealisedPricePNL numeric(27,8) not null,
	RealisedFXPNL numeric(27,8) not null,
	UnRealisedPricePNL numeric(27,8) not null,
	UnRealisedFXPNL numeric(27,8) not null,
	CarryPNL numeric(27,8) not null,
	StartDt datetime not null,
	UpdateUserID int not null,
	DataVersion binary(8) not null,
	ManagementPerformanceFee numeric(27,8) not null,
	CurrencyId int not null,
	Cost numeric(27,8) not null,
	EndDt datetime,
	LastActionUserID int)