USE Keeley

create table DBO.Attribution_hst(
	PortfolioId int not null,
	PositionId int not null,
	ReferenceDate datetime not null,
	AttributionFundId int not null,
	TodayAdministratorPricePNL numeric(27,8),
	TodayAdministratorFundAdjustedPricePNL numeric(27,8),
	TodayAdministratorFXPNL numeric(27,8),
	TodayAdministratorFundAdjustedFXPNL numeric(27,8),
	TodayAdministratorCarryPNL numeric(27,8),
	TodayAdministratorFundAdjustedCarryPNL numeric(27,8),
	TodayAdministratorOtherPNL numeric(27,8),
	TodayAdministratorFundAdjustedOtherPNL numeric(27,8),
	TodayPricePNL numeric(27,8) not null,
	TodayFundAdjustedPricePNL numeric(27,8) not null,
	TodayFXPNL numeric(27,8) not null,
	TodayFundAdjustedFXPNL numeric(27,8) not null,
	TodayCarryPNL numeric(27,8) not null,
	TodayFundAdjustedCarryPNL numeric(27,8) not null,
	TodayOtherPNL numeric(27,8),
	TodayFundAdjustedOtherPNL numeric(27,8),
	TodayKeeleyPricePNL numeric(27,8) not null,
	TodayKeeleyFundAdjustedPricePNL numeric(27,8) not null,
	TodayKeeleyFXPNL numeric(27,8) not null,
	TodayKeeleyFundAdjustedFXPNL numeric(27,8) not null,
	TodayKeeleyCarryPNL numeric(27,8) not null,
	TodayKeeleyFundAdjustedCarryPNL numeric(27,8) not null,
	TodayFactsetPricePNL numeric(27,8),
	TodayFactsetFundAdjustedPricePNL numeric(27,8),
	TodayFactsetFXPNL numeric(27,8),
	TodayFactsetFundAdjustedFXPNL numeric(27,8),
	TodayFactsetCarryPNL numeric(27,8),
	TodayFactsetFundAdjustedCarryPNL numeric(27,8),
	TodayFactsetOtherPNL numeric(27,8),
	TodayFactsetFundAdjustedOtherPNL numeric(27,8),
	TodayBookAdjustedPricePNL numeric(27,8),
	TodayBookAdjustedFXPNL numeric(27,8),
	TodayBookAdjustedCarryPNL numeric(27,8),
	ITDAdministratorPricePNL numeric(27,8),
	ITDAdministratorFundAdjustedPricePNL numeric(27,8),
	ITDAdministratorFXPNL numeric(27,8),
	ITDAdministratorFundAdjustedFXPNL numeric(27,8),
	ITDAdministratorCarryPNL numeric(27,8),
	ITDAdministratorFundAdjustedCarryPNL numeric(27,8),
	ITDAdministratorOtherPNL numeric(27,8),
	ITDAdministratorFundAdjustedOtherPNL numeric(27,8),
	ITDPricePNL numeric(27,8) not null,
	ITDFundAdjustedPricePNL numeric(27,8) not null,
	ITDFXPNL numeric(27,8) not null,
	ITDFundAdjustedFXPNL numeric(27,8) not null,
	ITDCarryPNL numeric(27,8) not null,
	ITDFundAdjustedCarryPNL numeric(27,8) not null,
	ITDOtherPNL numeric(27,8),
	ITDFundAdjustedOtherPNL numeric(27,8),
	ITDKeeleyPricePNL numeric(27,8) not null,
	ITDKeeleyFundAdjustedPricePNL numeric(27,8) not null,
	ITDKeeleyFXPNL numeric(27,8) not null,
	ITDKeeleyFundAdjustedFXPNL numeric(27,8) not null,
	ITDKeeleyCarryPNL numeric(27,8) not null,
	ITDKeeleyFundAdjustedCarryPNL numeric(27,8) not null,
	ITDFactsetPricePNL numeric(27,8),
	ITDFactsetFundAdjustedPricePNL numeric(27,8),
	ITDFactsetFXPNL numeric(27,8),
	ITDFactsetFundAdjustedFXPNL numeric(27,8),
	ITDFactsetCarryPNL numeric(27,8),
	ITDFactsetFundAdjustedCarryPNL numeric(27,8),
	ITDFactsetOtherPNL numeric(27,8),
	ITDFactsetFundAdjustedOtherPNL numeric(27,8),
	ITDBookAdjustedPricePNL numeric(27,8),
	ITDBookAdjustedFXPNL numeric(27,8),
	ITDBookAdjustedCarryPNL numeric(27,8),
	StartDt datetime not null,
	UpdateUserID int not null,
	DataVersion binary(8) not null,
	AdjustmentFactor numeric(27,8) not null,
	AdministratorAdjustmentFactor numeric(27,8),
	KeeleyAdjustmentFactor numeric(27,8) not null,
	TodayValuationPricePNL numeric(27,8),
	TodayValuationFundAdjustedPricePNL numeric(27,8),
	TodayValuationFXPNL numeric(27,8),
	TodayValuationFundAdjustedFXPNL numeric(27,8),
	TodayValuationCarryPNL numeric(27,8),
	TodayValuationFundAdjustedCarryPNL numeric(27,8),
	ITDValuationPricePNL numeric(27,8),
	ITDValuationFundAdjustedPricePNL numeric(27,8),
	ITDValuationFXPNL numeric(27,8),
	ITDValuationFundAdjustedFXPNL numeric(27,8),
	ITDValuationCarryPNL numeric(27,8),
	ITDValuationFundAdjustedCarryPNL numeric(27,8),
	ValuationAdjustmentFactor numeric(27,8),
	PercentageOfFund numeric(27,8) not null,
	KeeleyIsMaster bit not null,
	PreviousAttributionId int,
	EndDt datetime,
	LastActionUserID int)