USE Keeley

create table DBO.Attribution_hst(
	AttributionID int not null,
	PositionId int not null,
	ReferenceDate datetime not null,
	ITDFundAdministratorPrice numeric(27,8),
	ITDFundAdministratorFX numeric(27,8),
	ITDFundAdministratorCarry numeric(27,8),
	ITDFundAdministratorOther numeric(27,8),
	ITDFundKeeleyPrice numeric(27,8),
	ITDFundKeeleyFX numeric(27,8),
	ITDFundKeeleyCarry numeric(27,8),
	ITDBookKeeleyPrice numeric(27,8),
	ITDBookKeeleyFX numeric(27,8),
	ITDBookKeeleyCarry numeric(27,8),
	ITDFundValuationPrice numeric(27,8),
	ITDFundValuationFX numeric(27,8),
	ITDFundValuationCarry numeric(27,8),
	ITDFundFactsetPrice numeric(27,8),
	ITDFundFactsetFX numeric(27,8),
	ITDFundFactsetCarry numeric(27,8),
	ITDBookFactsetPrice numeric(27,8),
	ITDBookFactsetFX numeric(27,8),
	ITDBookFactsetCarry numeric(27,8),
	ITDFundPrice numeric(27,8) not null,
	ITDFundFX numeric(27,8) not null,
	ITDFundCarry numeric(27,8) not null,
	ITDBookPrice numeric(27,8),
	ITDBookFX numeric(27,8),
	ITDBookCarry numeric(27,8),
	TodayFundAdministratorPrice numeric(27,8),
	TodayFundAdministratorFX numeric(27,8),
	TodayFundAdministratorCarry numeric(27,8),
	TodayFundAdministratorOther numeric(27,8),
	TodayFundKeeleyPrice numeric(27,8),
	TodayFundKeeleyFX numeric(27,8),
	TodayFundKeeleyCarry numeric(27,8),
	TodayBookKeeleyPrice numeric(27,8),
	TodayBookKeeleyFX numeric(27,8),
	TodayBookKeeleyCarry numeric(27,8),
	TodayFundValuationPrice numeric(27,8),
	TodayFundValuationFX numeric(27,8),
	TodayFundValuationCarry numeric(27,8),
	TodayFundFactsetPrice numeric(27,8),
	TodayFundFactsetFX numeric(27,8),
	TodayFundFactsetCarry numeric(27,8),
	TodayBookFactsetPrice numeric(27,8),
	TodayBookFactsetFX numeric(27,8),
	TodayBookFactsetCarry numeric(27,8),
	TodayFundPrice numeric(27,8) not null,
	TodayFundFX numeric(27,8) not null,
	TodayFundCarry numeric(27,8) not null,
	TodayBookPrice numeric(27,8),
	TodayBookFX numeric(27,8),
	TodayBookCarry numeric(27,8),
	StartDt datetime not null,
	UpdateUserID int not null,
	DataVersion binary(8) not null,
	PortfolioId int,
	OpeningBookNav numeric(27,8),
	OpeningFundNav numeric(27,8),
	CapitalChangeBook numeric(27,8),
	CapitalChangeFund numeric(27,8),
	AdministratorOpeningNav numeric(27,8),
	OpeningValuationNav numeric(27,8),
	TotalContributionSinceLastValuation numeric(27,8),
	EndDt datetime,
	LastActionUserID int)