USE Keeley

create table DBO.Attribution_hst(
	AttributionID int not null,
	PositionId int not null,
	ReferenceDate datetime not null,
	ITDFundAdministratorPrice numeric(27,8),
	ITDFundAdministratorFX numeric(27,8),
	ITDFundAdministratorCarry numeric(27,8),
	ITDFundAdministratorOther numeric(27,8),
	ITDFundKeeleyPrice numeric(27,8) not null,
	ITDFundKeeleyFX numeric(27,8) not null,
	ITDFundKeeleyCarry numeric(27,8) not null,
	ITDBookKeeleyPrice numeric(27,8) not null,
	ITDBookKeeleyFX numeric(27,8) not null,
	ITDBookKeeleyCarry numeric(27,8) not null,
	ITDFundValuationPrice numeric(27,8),
	ITDFundValuationFX numeric(27,8),
	ITDFundValuationCarry numeric(27,8),
	ITDFundFactsetPrice numeric(27,8),
	ITDFundFactsetFX numeric(27,8),
	ITDFundFactsetCarry numeric(27,8),
	ITDBookFactsetPrice numeric(27,8),
	ITDBookFactsetFX numeric(27,8),
	ITDBookFactsetCarry numeric(27,8),
	ITDFundPrice numeric(27,8) not null,
	ITDFundFX numeric(27,8) not null,
	ITDFundCarry numeric(27,8) not null,
	ITDBookPrice numeric(27,8) not null,
	ITDBookFX numeric(27,8) not null,
	ITDBookCarry numeric(27,8) not null,
	TodayFundAdministratorPrice numeric(27,8),
	TodayFundAdministratorFX numeric(27,8),
	TodayFundAdministratorCarry numeric(27,8),
	TodayFundAdministratorOther numeric(27,8),
	TodayFundKeeleyPrice numeric(27,8) not null,
	TodayFundKeeleyFX numeric(27,8) not null,
	TodayFundKeeleyCarry numeric(27,8) not null,
	TodayBookKeeleyPrice numeric(27,8) not null,
	TodayBookKeeleyFX numeric(27,8) not null,
	TodayBookKeeleyCarry numeric(27,8) not null,
	TodayFundValuationPrice numeric(27,8),
	TodayFundValuationFX numeric(27,8),
	TodayFundValuationCarry numeric(27,8),
	TodayFundFactsetPrice numeric(27,8),
	TodayFundFactsetFX numeric(27,8),
	TodayFundFactsetCarry numeric(27,8),
	TodayBookFactsetPrice numeric(27,8),
	TodayBookFactsetFX numeric(27,8),
	TodayBookFactsetCarry numeric(27,8),
	TodayFundPrice numeric(27,8) not null,
	TodayFundFX numeric(27,8) not null,
	TodayFundCarry numeric(27,8) not null,
	TodayBookPrice numeric(27,8) not null,
	TodayBookFX numeric(27,8) not null,
	TodayBookCarry numeric(27,8) not null,
	StartDt datetime not null,
	UpdateUserID int not null,
	DataVersion binary(8) not null,
	EndDt datetime,
	LastActionUserID int)