USE Keeley

create table DBO.AttributionPnl_hst(
	AttributionPnlId int not null,
	PortfolioId int not null,
	FundId int not null,
	PositionID int not null,
	ReferenceDate datetime not null,
	AttributionSourceId int not null,
	MarketValue numeric(15,2) not null,
	NetPosition numeric(15,2) not null,
	IsNetPositionLong bit not null,
	IsExposureLong bit not null,
	Exposure numeric(15,2) not null,
	ExposureDelta numeric(15,2) not null,
	TodayPricePnl numeric(15,2) not null,
	TodayFxPnl numeric(15,2) not null,
	TodayCarryPnl numeric(15,2) not null,
	StartDt datetime not null,
	UpdateUserID int not null,
	DataVersion binary(8) not null,
	AttributionNavId int not null,
	CurrencyId int not null,
	TodayOtherPnl numeric(15,2) not null,
	PnlTypeId int not null,
	Price numeric(27,8),
	PriceId int,
	PriceToPositionFXRate numeric(27,8),
	PriceToPositionFXRateId int,
	FXRate numeric(27,8),
	FXRateId int,
	BetaShortTerm numeric(27,8),
	BetaLongTerm numeric(27,8),
	TodayRealisedFXPnl numeric(27,8),
	TodayRealisedPricePnl numeric(27,8),
	TodayCashBenefit numeric(27,8),
	NotionalCost numeric(27,8),
	EndDt datetime,
	LastActionUserID int)