USE Keeley

create table DBO.Exposure_hst(
	ExposureId int not null,
	PositionId int not null,
	InstrumentMarketId int not null,
	PortfolioId int not null,
	ReferenceDate datetime not null,
	EquityExposure numeric(27,8),
	CurrencyExposure numeric(27,8),
	CommodityExposure numeric(27,8),
	FixedIncomeExposure numeric(27,8),
	OtherExposure numeric(27,8),
	StartDt datetime not null,
	UpdateUserID int not null,
	DataVersion binary(8) not null,
	GovernmentBondExposure numeric(27,8),
	ChangeEquityExposure numeric(27,8),
	ChangeCurrencyExposure numeric(27,8),
	ChangeCommodityExposure numeric(27,8),
	ChangeFixedIncomeExposure numeric(27,8),
	ChangeOtherExposure numeric(27,8),
	ChangeGovernmentBondExposure numeric(27,8),
	MaturityDate datetime,
	IsPrimaryExposure bit not null,
	IsLong bit not null,
	InterestRateExposure numeric(27,8),
	ChangeInterestRateExposure numeric(27,8),
	BetaLongTerm numeric(27,8) not null,
	BetaShortTerm numeric(27,8) not null,
	HedgeRatio numeric(27,8),
	EndDt datetime,
	LastActionUserID int)