USE Keeley

create table DBO.Financing_hst(
	FinancingId int not null,
	FundId int not null,
	InstrumentMarketId int not null,
	ReferenceDate datetime not null,
	CurrencyId int not null,
	CustodianId int not null,
	NetPosition numeric(27,8),
	Price numeric(27,8),
	Notional numeric(27,8),
	FinancingRate numeric(27,8) not null,
	BorrowRate numeric(27,8) not null,
	AllInRate numeric(27,8) not null,
	FinancingAccrual numeric(27,8),
	BorrowAccrual numeric(27,8),
	AllInAccrual numeric(27,8),
	StartDt datetime not null,
	UpdateUserID int not null,
	DataVersion binary(8) not null,
	OverborrowNotional numeric(27,8),
	OverborrowUnits numeric(27,8),
	OverborrowRate numeric(27,8),
	OverborrowAccrual numeric(27,8),
	MarginInterest numeric(27,8),
	CashInterest numeric(27,8),
	RelatedFinancingId int,
	IsDummy bit not null,
	OverborrowFinancingAccrual numeric(27,8),
	FinancingControlId int not null,
	RehypothecationEarning numeric(27,8),
	EndDt datetime,
	LastActionUserID int)