USE Keeley

create table DBO.Fund_hst(
	LegalEntityID int not null,
	CurrencyID int not null,
	StartDt datetime not null,
	UpdateUserID int not null,
	DataVersion binary(8) not null,
	PositionsExist bit not null,
	PerfFundName varchar(100),
	InstrumentMarketId int not null,
	BenchmarkInstrumentMarketId int not null,
	ParentFundId int,
	IsActive bit not null,
	FundTypeId int not null,
	PriceIsExternallyVisible bit not null,
	InceptionDate datetime not null,
	RiskFreeInstrumentMarketId int not null,
	DealingDateDefinitionId int not null,
	EZEIdentifier varchar(100),
	PortfolioIsExternallyVisible bit not null,
	AssetManagementCompanyId int not null,
	IntranetOrdering int,
	ReferenceFundId int,
	PerformanceFeeTypeId int not null,
	LossWarning numeric(27,8),
	LossTrigger numeric(27,8),
	ShareClassDescriptor varchar(50),
	PerformanceFee numeric(27,8),
	ManagementFee numeric(27,8) not null,
	AdministratorId int not null,
	AdministratorIdentifier varchar(100),
	IsVoting bit not null,
	ClientLoadDate datetime not null,
	IsDistributing bit not null,
	FundStructureId int not null,
	HasUKReportingStatus bit not null,
	IsClosedToNewInvestors bit not null,
	IsClosedToExistingInvestors bit not null,
	IsStaffOnly bit not null,
	IsIsaEligible bit not null,
	OtherCostRatio numeric(27,8),
	TotalCostRatio numeric(27,8),
	IsSynthetic bit not null,
	ClientMarketingTypeId int not null,
	IsMainRetailShareClass bit,
	PercentageHedged numeric(27,8),
	LockInYears int,
	IsLongOnly bit not null,
	IsMainPerformanceShareClass bit not null,
	IsSolvencyII bit not null,
	IsVAG bit not null,
	TakeOnDate datetime,
	IsAnalystPnl bit not null,
	CustodianId int,
	ManagerId int not null,
	ISCFDFullyFunded bit not null,
	IsCRR bit not null,
	TaxReferenceNumber varchar(100),
	FundFeederTypeId int,
	EndDt datetime,
	LastActionUserID int)