USE Keeley

create table DBO.FXTradeEvent_hst(
	EventID int not null,
	ReceiveCurrencyId int not null,
	PayCurrencyId int not null,
	ReceiveAmount numeric(27,8) not null,
	PayAmount numeric(27,8) not null,
	IsProp bit not null,
	EnteredMultiply bit not null,
	Ticket varchar(100),
	IsCancelled bit not null,
	CounterpartyId int not null,
	AmendmentNumber int not null,
	MaturityDate datetime not null,
	TraderId int not null,
	StartDt datetime not null,
	UpdateUserID int not null,
	DataVersion binary(8) not null,
	TradeDate datetime not null,
	IsForward bit not null,
	InputDate datetime not null,
	SettlementCurrencyId int not null,
	SupressFromExtracts bit not null,
	NonEuroPairReceiveToEuroFXRate numeric(27,8),
	NonEuroPairReceiveToEuroFXRateId int,
	IsRoll bit not null,
	ContraEventId int,
	InstrumentMarketId int not null,
	OriginalInputDate datetime not null,
	EndDt datetime,
	LastActionUserID int)