USE Keeley

create table DBO.InterestRateSwap_hst(
	InstrumentId int not null,
	StartDate datetime not null,
	MaturityDate datetime not null,
	NPVCurrencyId int not null,
	PayCurrencyId int not null,
	PaySpread numeric(27,8),
	PayNotional numeric(27,8) not null,
	PayIsFloating bit not null,
	PayRollConventionId int not null,
	PayDayCountConventionId int not null,
	PayCouponFrequency int not null,
	PayFixedRate numeric(27,8),
	PayFloatingIndexInstrumentMarketId int,
	ReceiveCurrencyId int not null,
	ReceiveSpread numeric(27,8),
	ReceiveNotional numeric(27,8) not null,
	ReceiveIsFloating bit not null,
	ReceiveRollConventionId int not null,
	ReceiveDayCountConventionId int not null,
	ReceiveCouponFrequency int not null,
	ReceiveFixedRate numeric(27,8),
	ReceiveFloatingIndexInstrumentMarketId int,
	StartDt datetime not null,
	UpdateUserID int not null,
	DataVersion binary(8) not null,
	PayFirstPaymentDate datetime not null,
	ReceiveFirstPaymentDate datetime not null,
	EndDt datetime,
	LastActionUserID int)