USE Keeley

create table DBO.PADealing_hst(
	PADealingID int not null,
	RequestUserID int not null,
	InstrumentMarketID int not null,
	PADealingAccountID int not null,
	RequestQuantity numeric(27,8),
	RequestValue numeric(27,8),
	RequestNotes varchar(150),
	RequestTimeStamp datetime not null,
	IsAutomaticRejection bit not null,
	RejectionReasonID int,
	ActualQuantity numeric(27,8),
	IsContractRecieved bit not null,
	IsComplianceApproved bit,
	ComplianceUserID int,
	ComplianceNotes varchar(150),
	ComplianceTimeStamp datetime,
	IsTraderApproved bit,
	TraderUserID int,
	TraderNotes varchar(150),
	TraderTimeStamp datetime,
	StartDt datetime not null,
	UpdateUserID int not null,
	DataVersion binary(8) not null,
	IsExistingHolding bit not null,
	IsPending bit not null,
	EndDt datetime,
	LastActionUserID int)