USE Keeley

create table DBO.ReportPositionStaticData_hst(
	PositionId int not null,
	IsEnvironmentPROD bit not null,
	InstrumentName varchar(200) not null,
	AssetClass varchar(70) not null,
	IssuerName varchar(70) not null,
	Sedol varchar(150),
	BloombergTicker varchar(150),
	InstrumentClassId int not null,
	DerivedAssetClassId int not null,
	Custodian varchar(70) not null,
	AccountType varchar(100) not null,
	Fund varchar(70) not null,
	Region varchar(100) not null,
	Country varchar(100) not null,
	GICSSector varchar(100),
	GICSIndustry varchar(100),
	GICSIndustryGroup varchar(100),
	GICSSubIndustry varchar(100),
	DefaultSector varchar(100),
	IndustryName varchar(100) not null,
	Account varchar(100) not null,
	InstrumentClassName varchar(100) not null,
	PositionCurrency varchar(200) not null,
	Book varchar(70) not null,
	Isin varchar(150),
	ParentInstrumentClass varchar(100),
	FundCurrency varchar(200) not null,
	FundType varchar(70) not null,
	CompanySize varchar(100) not null,
	Analyst varchar(100),
	Strategy varchar(100),
	Manager varchar(100),
	ListingStatus varchar(100) not null,
	IsProp bit,
	IsPrimary bit not null,
	MarketCapUSD numeric(15,0),
	IsAccrual bit not null,
	CountryOfDomicile varchar(100),
	BaseCurrencyId int not null,
	ExposureCurrency varchar(200) not null,
	InstrumentMarketId int not null,
	FundInstrumentMarketId int not null,
	IssuerId int not null,
	CisFundId int,
	CisFundShareClassId int,
	PriceCurrency varchar(200) not null,
	UnderlyingInstrumentMarketId int,
	UnderlyingInstrumentId int,
	CustodianId int not null,
	AccountTypeId int not null,
	RegionId int not null,
	CountryId int not null,
	GICSSectorId int,
	GICSIndustryId int,
	GICSIndustryGroupId int,
	GICSSubIndustryId int,
	DefaultSectorId int,
	DefaultIndustryId int not null,
	AccountId int not null,
	PositionCurrencyId int not null,
	BookId int not null,
	FundCurrencyId int not null,
	AnalystId int,
	StrategyId int,
	ManagerId int,
	CountryOfDomicileId int,
	PriceCurrencyId int not null,
	FundStructure varchar(100) not null,
	ForwardFxContraCurrencyId int,
	ForwardFxBaseCurrencyId int,
	CountryOfListingId int not null,
	CountryOfListing varchar(100) not null,
	ListingStatusId int not null,
	MaturityDate datetime,
	IsPut bit,
	ParentInstrumentClassId int,
	FundIsLongOnly bit not null,
	InternalOriginatorId int,
	InternalOriginatorType int,
	InternalOriginator varchar(100),
	InternalOriginatorId2 int,
	InternalOriginatorType2 int,
	InternalOriginator2 varchar(100),
	ExternalOriginatorId int,
	ExternalOriginator varchar(100),
	ExternalOriginatorEntity varchar(100),
	OriginatingDate datetime,
	IsOriginatedLong bit,
	FundManager varchar(100) not null,
	FundManagerId int not null,
	DefaultIndustry varchar(100),
	DataVersion binary(8) not null,
	StartDt datetime not null,
	UpdateUserID int not null,
	EndDt datetime,
	LastActionUserID int)