USE Keeley

create table DBO.TradeEvent_hst(
	EventID int not null,
	InstrumentMarketID int not null,
	TradeDate datetime not null,
	SettlementDate datetime not null,
	TraderId int not null,
	GrossPrice numeric(35,16) not null,
	NetPrice numeric(35,16) not null,
	Quantity numeric(27,8) not null,
	BuySellReasonId int not null,
	TradedNet bit not null,
	PriceIsClean bit not null,
	TradeCurrencyId int not null,
	SettlementCurrencyId int not null,
	NetConsideration numeric(27,8) not null,
	GrossConsideration numeric(27,8) not null,
	CounterpartyId int not null,
	TradeSettlementFXRate numeric(35,16) not null,
	TradeSettlementFXRateMultiply bit not null,
	TradeInstrumentFXRate numeric(35,16) not null,
	TradeInstrumentFXRateMultiply bit not null,
	Ticket varchar(100),
	IsCancelled bit not null,
	AmendmentNumber int not null,
	StartDt datetime not null,
	UpdateUserID int not null,
	DataVersion binary(8) not null,
	InputDate datetime not null,
	SupressFromExtracts bit not null,
	TradeEuroFXRate numeric(27,8) not null,
	TradeEuroFXRateId int,
	IsRoll bit not null,
	ContraEventId int,
	OriginalInputDate datetime not null,
	IndexRatio numeric(27,8),
	TradeDateAsDate date not null,
	RealisedPnlBookCurrency numeric(27,8),
	RealisedPnlInstrumentCurrency numeric(27,8),
	CostPriceOverride numeric(27,8),
	EndDt datetime,
	LastActionUserID int)